game_stats:
  outputs:
    # Environment for runnning script locally and in Google Cloud
    prod:
      method: oauth
      dataset: game_stats
      priority: interactive
      project: "{{ env_var('GOOGLE_PROJECT_ID') }}"
      threads: 60
      type: bigquery

    # Environment for running script in Docker container
    dev:
      method: service-account
      dataset: game_stats
      priority: interactive
      project: "{{ env_var('GOOGLE_PROJECT_ID') }}"
      keyfile: /root/gcloud_key.json
      threads: 60
      type: bigquery

  target: prod
