game_stats:
  outputs:
    dev:
      dataset: game_stats
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: "{{ env_var('GOOGLE_PROJECT_ID') }}"
      threads: 60
      type: bigquery
  target: dev
