analytics:
  outputs:
    prod:
      method: oauth
      dataset: game_stats
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT_ID') }}"
      threads: 64
      location: EU
      type: bigquery

  target: prod
