# Configuration file for deploying code to Google Cloud

steps:

  # Build Docker images

  - id: "Build web_scraping image" 
    name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "Dockerfile.scraping", "-t", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/web_scraping:$COMMIT_SHA", "."]
    dir: "pipeline/python/"

  - id: "Build data_transformations image" 
    name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "Dockerfile.pandas", "-t", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/data_transformations:$COMMIT_SHA", "."]
    dir: "pipeline/python/"

  - id: "Build dbt image" 
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt:$COMMIT_SHA", "."]
    dir: "pipeline/dbt/"


  # Push images to Artifact Registry

  - id: "Push web_scraping image to Registry" 
    name: gcr.io/cloud-builders/docker
    args: ["push", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/web_scraping:$COMMIT_SHA"]

  - id: "Push data_transformations image to Registry" 
    name: gcr.io/cloud-builders/docker
    args: ["push", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/data_transformations:$COMMIT_SHA"]

  - id: "Push dbt image to Registry" 
    name: gcr.io/cloud-builders/docker
    args: ["push", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt:$COMMIT_SHA"]


  # Deploy containers to Cloud Run as Jobs

  - id: "Deploy web_scraping container"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [
      "run", "jobs", "deploy", "game-stats-web-scraping",
      "--image", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/web_scraping:$COMMIT_SHA",
      "--region", "$_DEPLOY_REGION",
      "--project", "$PROJECT_ID",
      # Job configuration
      "--max-retries=1",
      "--task-timeout=30m",
      "--cpu=2",
      "--memory=1Gi",
      # Provide env variables from cloudbuild
      "--set-env-vars=BUCKET_NAME=$_BUCKET_NAME", 
      "--set-env-vars=DATASET_NAME=$_DATASET_NAME",
      "--set-env-vars=BASE_URL=$_BASE_URL",
      "--set-env-vars=GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID",
    ]

  - id: "Deploy data_transformations container"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [
      "run", "jobs", "deploy", "game-stats-data-transformations",
      "--image", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/data_transformations:$COMMIT_SHA",
      "--region", "$_DEPLOY_REGION",
      "--project", "$PROJECT_ID",
      # Job configuration
      "--max-retries=1",
      "--task-timeout=10m",
      "--cpu=2",
      "--memory=1Gi",
      # Provide env variables from cloudbuild
      "--set-env-vars=BUCKET_NAME=$_BUCKET_NAME", 
      "--set-env-vars=DATASET_NAME=$_DATASET_NAME",
      "--set-env-vars=BASE_URL=$_BASE_URL",
      "--set-env-vars=GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID",
    ]

  - id: "Deploy dbt container"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [
      "run", "jobs", "deploy", "game-stats-dbt",
      "--image", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt:$COMMIT_SHA",
      "--region", "$_DEPLOY_REGION",
      "--project", "$PROJECT_ID",
      # Job configuration
      "--max-retries=1",
      "--task-timeout=10m",
      "--cpu=2",
      "--memory=1Gi",
      # Provide env variables from cloudbuild
      "--set-env-vars=DATASET_NAME=$_DATASET_NAME",
      "--set-env-vars=GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID",
    ]


  # Update Workflows YAML file

  - id: "Update Workflows YAML file"
    name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'workflows', 'deploy', '$_WORKFLOW_NAME',
      '--source', 'cloud/workflow.yml',
      "--location", "$_DEPLOY_REGION",
      "--set-env-vars=PROJECT_ID=$PROJECT_ID",
      "--set-env-vars=DEPLOY_REGION=$_DEPLOY_REGION",
    ]   


options:
  logging: CLOUD_LOGGING_ONLY


