steps:

  # Python
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/python-script:$COMMIT_SHA", "."]
    dir: "python/"
  
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/python-script:$COMMIT_SHA"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - beta
      - run
      - jobs
      - deploy
      - python-script
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/python-script:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION


  # DBT
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt-script:$COMMIT_SHA", "."]
    dir: "dbt/"
  
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt-script:$COMMIT_SHA"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - beta
      - run
      - jobs
      - deploy
      - dbt-script
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt-script:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION


  # Deploy the workflow
  - id: 'deploy-workflow'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['workflows', 'deploy', '$_WORKFLOW_NAME-$BRANCH_NAME', '--source', 'cloud/workflow.yml']   

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/python-script:$COMMIT_SHA'
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt-script:$COMMIT_SHA'