steps:

  # Python

  - id: "build python image from git repo"
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/python-script:$COMMIT_SHA", "."]
    dir: "python/"

  - id: "push python image to cloud registry" 
    name: gcr.io/cloud-builders/docker
    args: ["push", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/python-script:$COMMIT_SHA"]

  - id: "deploy python container to cloud run"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - beta
      - run
      - jobs
      - deploy
      - python-script
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/python-script:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION


  # DBT

  - id: "build dbt image from git repo"
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt-script:$COMMIT_SHA", "."]
    dir: "dbt/"
  

  - id: "push dbt image to cloud registry" 
    name: gcr.io/cloud-builders/docker
    args: ["push", "$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt-script:$COMMIT_SHA"]


  - id: "deploy dbt container to cloud run"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - beta
      - run
      - jobs
      - deploy
      - dbt-script
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt-script:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION


  # Deploy the workflow 

  - id: "deploy workflow with the latest images"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['workflows', 'deploy', '$_WORKFLOW_NAME', '--source', 'cloud/workflow.yml', "--location", "$_DEPLOY_REGION"]   


options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/python-script:$COMMIT_SHA'
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/dbt-script:$COMMIT_SHA'