# Configuration file that defines a sequence of jobs executed in Google Cloud Workflows.

main:
  steps:
    # Set env variables
    - init:
        assign:
          - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - region: europe-central2

    # Chain python and dbt scripts

    - web_scraping:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "web-scraping"}
          location: ${region}
        result: web_scraping_result
        next: pandas_transformations

    - pandas_transformations:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "pandas-transformations"}
          location: ${region}
        result: pandas_transformations_result
        next: dbt
    
    - dbt:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "dbt"}
          location: ${region}     
        result: dbt_result
