main:
  steps:

    # Create env variables
    - init:
        assign:
          - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - region: europe-central2

    # Sequentially run Python and DBT scripts as Cloud Run jobs
    - python_script:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "python-script"}
          location: ${region}

    - dbt_script:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "dbt-script"}
          location: ${region}
