# Configuration file for Google Cloud Workflows

main:
  steps:

    # Use env variables from Cloud Build

    - init:
        assign:
          - project_id: ${sys.get_env("PROJECT_ID")}
          - region: ${sys.get_env("DEPLOY_REGION")}

    # Run sequentially Docker containers deployed as Cloud Run Jobs

    - web_scraping:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "game-stats-web-scraping"}
          location: ${region}
        next: data_transformations

    - data_transformations:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "game-stats-data-transformations"}
          location: ${region}
        next: dbt

    - dbt:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "game-stats-dbt"}
          location: ${region}