main:
  steps:
    # Set env variables
    - init:
        assign:
          - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - region: europe-central2

    # Run sequentially jobs

    - web_scraping:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "web-scraping"}
          location: ${region}
        result: web_scraping_result
        next: data_transformations

    - data_transformations:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "data-transformations"}
          location: ${region}
        result: data_transformations_result
        next: dbt
    
    - dbt:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "dbt"}
          location: ${region}     
        result: dbt_result
        next: finish

    - finish:
        return: ${dbt_result}
