main:
  steps:

    - init:
        assign:
          - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - region: europe-central2
    
    - python_script:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "python-script"}
          location: ${region}
        result: python_script_output

    - dbt_script:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project_id + "/jobs/" + "dbt-script"}
          location: ${region}
        result: dbt_script_output

    - finish:
        return:
            python_script: ${python_script_output}
            dbt_script: ${dbt_script_output}