name: 'game_stats'
version: '1.0.0'
profile: 'game_stats'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

models:
  game_stats:
    # New dataset for ready for analytics tables
    +materialized: table
    +schema: analytics

seeds:
  game_stats:
    +schema: analytics