FROM python:3.12-slim

WORKDIR /script

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY web_scraping ./web_scraping
COPY gcp_utils.py .

CMD [ "python", "web_scraping/main.py" ]