game_stats:
  outputs:
    prod:
      method: oauth
      priority: interactive
      dataset: "{{ env_var('DATASET_NAME') }}"
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT_ID') }}"
      threads: 64
      type: bigquery

  target: prod
