FROM python:3.12-slim

WORKDIR /script

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY data_transformations ./data_transformations
COPY gcp_utils.py .

CMD [ "python", "data_transformations/main.py" ]